### ISSUE TITLE
Committer Responsibilities:  Issue maintenance permissions for all repositories

### ISSUE THREAD

**Issue by SaPeresi** [genevaers/community#64]
This is an issue around the maintenance of issues of adding a label and maintaining the assignee for the issue.  It does not appear that anyone can add a label or change the assignee if they are not a committer on the repository.  This is a very restrictive rule.  Can this be changed? 

When adding this issue I cannot assign to anyone or add a label on this either.

**Comment by SaPeresi** [comment]
Even after adding I cannot assign or put a label on.

**Comment by jmertic** [comment]
That is by design; generally those individuals who are committers would be the ones triaging issues.

One way I do see communities automate this process is through the use of a CODEOWNERS file, which can automatically request reviews from the committers responsible for areas of the code base. Learn more about it at https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/about-code-owners/. 

In addition, using issue templates and pull request templates can be used for automatically applying labels based on the issue coming in. We use this extensively for OMP for this purpose, as well as to provide a template for issues and pull requests. Learn more at https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/about-issue-and-pull-request-templates

Let me know if this helps address the concern!

**Comment by AOrthVector** [comment]
Andrea will assign herself to this issue to research links provided by John

**Comment by KipTwitchell** [comment]
Committer responsibilities established.

**Comment by KipTwitchell** [comment]
Having discussed at TSC, this meeting is considered closed.
